contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #latihan channel"
    url: https://nfcore.slack.com/channels/latihan
    about: Discussion about the nf-core/latihan pipeline
